"use client";
import { useState } from "react";
import { X, Copy, Check } from "lucide-react";

function buildDataFile(lineups) {
  const header = "// Generated by admin mode. Replace the contents of data/lineups.js with this.\n";
  return header + "export const LINEUPS = " + JSON.stringify(lineups, null, 2) + ";\n";
}

export default function ExportModal({ lineups, onClose }) {
  const [copied, setCopied] = useState(false);
  const text = buildDataFile(lineups);
  async function copy() {
    try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch {}
  }
  return (
    <div className="ub-overlay" onClick={onClose}>
      <div className="ub-modal" onClick={(e) => e.stopPropagation()}>
        <button className="ub-close" onClick={onClose}><X size={18} /></button>
        <div className="ub-form-head"><div className="ub-hero-kicker">Admin · export</div><h2>Save all lineups</h2></div>
        <div className="ub-snippet">
          <p className="ub-snippet-intro">Replace the whole contents of <code>data/lineups.js</code> with this to persist your edits and deletions:</p>
          <textarea readOnly value={text} onClick={(e) => e.target.select()} />
          <div className="ub-snippet-actions">
            <button className="ub-btn-primary" onClick={copy}>{copied ? <><Check size={15} /> Copied</> : <><Copy size={15} /> Copy all</>}</button>
            <button className="ub-btn-ghost" onClick={onClose}>Done</button>
          </div>
        </div>
      </div>
    </div>
  );
}
